_target_: model_merging.data.dataset.load_dataset
name: SVHN
ft_epochs: 4
preprocess_fn: ???
classnames_override:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
hf_dataset: 
  _target_: datasets.load_dataset
  _args_:
    - Genius-Society/svhn
