
defaults:
  - _self_

_target_: model_merging.model.muon_image_classifier.MuonImageClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}

optimizer:
  lr: 0.002       # Muon lr for encoder 2D weights
  adamw_lr: 3e-5  # AdamW lr for biases, norms, embeddings, head
  adamw_wd: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_epochs}
