
defaults:
  - _self_

_target_: model_merging.model.multitask_classifier.MultiTaskImageClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
dataset_names: {eval_dataset}

image_encoder: ??  
classification_heads: ??

#optimizer:
#  _target_: torch.optim.AdamW
#  lr: 1e-5
#  weight_decay: 0.1
  
optimizer:
  lr: 0.02          # Muon lr for hidden weights
  adamw_lr: 3e-4    # AdamW lr for everything else
  adamw_wd: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_epochs}
