_target_: model_merging.merger.dual_merging.DualCommonTaskSpecificMerger

optimal_alphas:
  ViT-B-32:
    8: 1.0
    14: 1.2
  
    20: 1.70
  ViT-B-16:
    8: 1.40
    14: 1.20
    20: 1.00
  ViT-L-14:
    8: 1.50
    14: 1.30
    20: 1.00


device: ${device}
model_name: ${nn.encoder.model_name}
svd_path: "${oc.env:MODELS_PATH}svd_dict_${nn.encoder.model_name}.pt"
svd_compress_factor: null 
common_space_fraction: 0.8
