_target_: model_merging.merger.arithmetic_merger.TaskArithmeticMerger
optimal_alpha: 1.0
svd_path: "${oc.env:MODELS_PATH}svd_dict_${nn.encoder.model_name}.pt"
#svd_compress_factor: 16.5
svd_compress_factor: 1.0
device: ${device}
model_name: ${nn.encoder.model_name}
low_rank_factor: 1.0
